### PR TITLE
Require graph tips to be sorted

### PR DESCRIPTION
**Pull request by cafca**
Previous discussion in https://github.com/p2panda/p2panda/pull/277#pullrequestreview-913353816

### CODE REVIEW

**Comment by adzialocha** [comment]
I'm not 100% sold on the idea that we _need_ to do this. As @sandreae pointed out we introduce a spec requirement without any large impact.

Related: https://github.com/p2panda/p2panda/issues/283

**Comment by sandreae** [comment]
I'm in favour of avoiding adding the sorted requirement to `DocumentViewId` to the spec. I'm happy with all of the implementation approaches though. Will follow up with that thought here: https://github.com/p2panda/p2panda/issues/283

**Comment by cafca** [comment]
I am strongly in favor of requiring sorted values in all CBOR arrays where the order of values doesn't carry information. This will ensure that an operation's encoding is deterministic, makes comparing values easier and has probably lots of other advantages down the line.

**Comment by cafca** [comment]
Superseded by https://github.com/p2panda/handbook/issues/164

**Pull request closed without merging**
